tiendaAqp/cafeteria/urls.py
from django.urls import include, path
from . import views
from rest_framework import routers
from rest_framework.documentation import include_docs_urls

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'categorias', views.CategoriaViewSet)
router.register(r'productos', views.ProductoViewSet)
router.register(r'pedidos', views.PedidoViewSet)


urlpatterns = [
    path('', views.index, name = 'index'),
    path('produtos/', views.ProductoListView.as_view(), name = 'productos'),
    path('categorias/', views.CategoriaListView.as_view(), name = 'categorias'),
    path('produto/<int:pk>', views.ProductoDetailView.as_view(), name='producto'),
    path('pedidos/', views.PedidoListView.as_view(), name = 'pedidos'),
    path('addCliente/', views.clienteCreateView, name = 'addcliente'),
    path('pedir/', views.pedidoCreateView, name='hacer_pedido'),
    #paraoteraciones crud
    path('apiRest/', include('rest_framework.urls')),
    path('administracion/', include(router.urls), name='administrar'),
    path('doc/', include_docs_urls(title='documentacion')),
]

tiendaAqp/tiendaAqp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cafeteria/', include('cafeteria.urls')),
    path('', RedirectView.as_view(url='cafeteria/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tiendaAqp/cafeteria/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Cliente(models.Model):
    nombre = models.CharField(max_length=100)
    email = models.EmailField()
    telefono = models.CharField(max_length=20)

    def __str__(self):
        return self.nombre
    
    class Meta:
        ordering = ['nombre']

    def get_absolute_url(self):
        return reverse('cliente-detail', args=[str(self.id)])


class Categoria(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre


class Producto(models.Model):
    nombre = models.CharField(max_length=100)
    imagen = models.ImageField(upload_to= 'pics')
    descripcion = models.TextField()
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    categoria = models.ForeignKey('Categoria', on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('producto', args=[str(self.id)]) # debe ser igual a name de view
    
    def __str__(self):
        return self.nombre


class Pedido(models.Model):
    cliente = models.ForeignKey('Cliente', on_delete=models.CASCADE)
    fecha = models.DateTimeField(auto_now_add=True)
    productos = models.ManyToManyField('Producto', through='ItemPedido')
    ESTADOS_PEDIDO = [
        ('P', 'Pendiente'),
        ('E', 'En preparación'),
        ('C', 'Completado'),
    ]
    estado = models.CharField(max_length=1, choices=ESTADOS_PEDIDO, default='P')

    def get_estado_display(self):
        return dict(self.ESTADOS_PEDIDO)[self.estado]
    
    def __str__(self):
        return f"Pedido {self.cliente} - {self.id}"

    def get_absolute_url(self):
        return reverse('pedido', args=[str(self.id)])

class ItemPedido(models.Model):
    pedido = models.ForeignKey('Pedido', on_delete=models.CASCADE)
    producto = models.ForeignKey('Producto', on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField()

    def subtotal(self):
        return self.cantidad * self.producto.precio

    def __str__(self):
        return f"Pedido {self.producto.nombre}, Cantidad {self.cantidad}, Precio unitario {self.producto.precio}"


class Carrito(models.Model):
    cliente = models.OneToOneField('Cliente', on_delete=models.CASCADE)
    productos = models.ManyToManyField('Producto', through='ItemCarrito')

    def __str__(self):
        return f"Carrito de {self.cliente.nombre}"


class ItemCarrito(models.Model):
    carrito = models.ForeignKey('Carrito', on_delete=models.CASCADE)
    producto = models.ForeignKey('Producto', on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField()

    def __str__(self):
        return f"{self.cantidad} de {self.producto.nombre} en {self.carrito}"


class ReservaMesa(models.Model):
    cliente = models.ForeignKey('Cliente', on_delete=models.CASCADE)
    fecha = models.DateField()
    hora = models.TimeField()
    cantidad_personas = models.PositiveIntegerField()

    def __str__(self):
        return f"Reserva para {self.cantidad_personas} personas el {self.fecha} a las {self.hora}"

tiendaAqp/cafeteria/forms.py
from django import forms
from .models import Pedido

class RawClienteForm(forms.Form):
    nombre = forms.CharField(label='Nombre', 
        widget=forms.TextInput(
            attrs={
                'placeholder':'ingresa solo tu nombre',
                'id': 'nombre',
                'class': 'form-control',
                'data-rule': 'minlen:1',
            }
            
        )
    )
    
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                'placeholder':'ingresa tu email',
                'id': 'email',
                'class': 'form-control',
                'data-rule': 'minlen:1',
            }
            
        )
    )
    
    telefono = forms.IntegerField(
        widget=forms.NumberInput(
            attrs={
                'placeholder':'ingresa tu telefono',
                'id': 'telefono',
                'class': 'form-control',
                'data-rule': 'minlen:1',
            }
            
        )
    )

#para pedidos
class RawPedidoForm(forms.ModelForm):
    class Meta:
        model = Pedido
        fields = ['cliente', 'productos', 'estado']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        self.fields['cliente'].widget = forms.HiddenInput()
        self.fields['productos'].widget = forms.HiddenInput()
        self.fields['estado'].widget = forms.HiddenInput()

tiendaAqp/cafeteria/views.py
from django.shortcuts import render, redirect
from django.views import generic
from .models import * # cliente, categoria, producto, pedido, itempedido, carrito, itemcarrito, reserva
from django.shortcuts import get_object_or_404
from .forms import RawClienteForm, RawPedidoForm
from rest_framework import viewsets
from .serializer import * # ProductoSerializer
from django.contrib.auth.models import User

# Create your views here.

def index(request):
    # num_categoria = Categoria.objects.all().count()
    # num_producto = Producto.objects.all().count()
    # num_cliente = Cliente.objects.count()
    # num_pendiente = Pedido.objects.filter(estado='P').count()

    icono = ('bi bi-hand-thumbs-up', 'bi bi-check2-square', 'bi bi-hourglass')
    caracteristica = ('Compromiso', 'Seguridad', 'Eficacia')
    descripcion_caracteristica = (
        'Tendrás tus pedidos sin falta',
        'Tus pedidos se preparan con todos los protocolos de seguridad',
        'Sabemos que tu tiempo es valioso',
    )
    caracteristicas_combinadas = zip(icono, caracteristica, descripcion_caracteristica)

    espacios = ('img/espacios/e1.jpeg', 'img/espacios/e2.jpg', 'img/espacios/e3.jpeg')
    
    nombre = ('André', 'Melsy', 'Frank\'s', 'Jhamil')
    imagen_colab = ('img/chefs/chefs-1.jpg', 'img/chefs/chefs-2.jpg', 'img/chefs/chefs-3.jpg', 'img/chefs/chefs-3.jpg')
    colaboracion = ('colaboración 1', 'colaboración 2', 'colaboración 3', 'colaboración 4')
    descripcion = ('primero', 'segundo', 'tercero', 'cuarto')
    colaboradores_combinadas = zip(nombre, imagen_colab, colaboracion, descripcion)
    
    context = {
        'caracteristicas_combinadas': caracteristicas_combinadas,
        'espacios': espacios,
        'colaboradores_combinadas': colaboradores_combinadas,
    }

    return render(request, 'index.html', context=context)

class CategoriaListView(generic.ListView):
    model = Categoria
    
    context_object_name = 'categoria_list'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        categorias = Categoria.objects.all()
        context['categorias'] = categorias
        return context

class ProductoListView(generic.ListView):
    model = Producto

    context_object_name = 'producto_list'

    def get_context_data(self, **kwargs):
        context = super(ProductoListView, self).get_context_data(**kwargs)
        context['uno contexto'] = 'algo más'
        return context
    
    def get_queryset(self):
        return Producto.objects.all() #filter(title__icontains='war')[:5]
    
    #template_name = 'books/my_arbitrary_template_name_list.html'

class ReservaMesaListView(generic.ListView):
    model = ReservaMesa

class PedidoListView(generic.ListView):
    model = Pedido
    
    def pedidos_monto_total(self, obj):
        total = sum(item.subtotal() for item in obj.itempedido_set.all())
        return total

## vistas detalladas 
class ProductoDetailView(generic.DetailView):
    model = Producto

class PedidoDetailView(generic.DetailView):
    model = Pedido


def producto_detail_view(request, primary_key):
    producto = get_object_or_404(Producto, pk=primary_key)
    return render(request, 'cafeteria/producto_detail.html', context={'producto': producto})

def clienteCreateView(request):
    form = RawClienteForm()
    if(request.method == 'POST'):
        form = RawClienteForm(request.POST)
        if(form.is_valid()):
            print(form.cleaned_data)
            Cliente.objects.create(**form.cleaned_data)
            return redirect('index')
        else:
            print(form.errors)
    
    context = {
        'form' : form
    }
    return render(request, 'cafeteria/cliente_create.html', context)

def pedidoCreateView(request):
    if request.method == 'POST':
        producto_id = request.POST.get('producto_id')
        producto = Producto.objects.get(id=producto_id)
        cantidad = int(request.POST.get('cantidad', 1))
        nombre = request.POST.get('nombre')
        email = request.POST.get('email')
        
        try:
            cliente = Cliente.objects.get(nombre=nombre, email=email)
        except Cliente.DoesNotExist:
            return redirect('addcliente')
        
        pedido = Pedido.objects.create(
            cliente=cliente,
            estado='P'
        )
        pedido.productos.add(producto, through_defaults={'cantidad': cantidad})

        return redirect('productos')

    return render(request, 'cafeteria/producto_detail.html')

#djangorest (CRUD)
class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

class CategoriaViewSet(viewsets.ModelViewSet):
    queryset = Categoria.objects.all()
    serializer_class = CategoriaSerializer

class ProductoViewSet(viewsets.ModelViewSet):
    queryset = Producto.objects.all()
    serializer_class = ProductoSerializer

class PedidoViewSet(viewsets.ModelViewSet):
    queryset = Pedido.objects.all()
    serializer_class = PedidoSerializer
    

tiendaAqp/cafeteria/templates/cafeteria/categoria_list.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <section id="menu" class="menu">
        <div class="container" data-aos="fade-up">

            <div class="section-header">
                <h2>Lo que ofrecdemos</h2>
                <p>Revisa a detalle las categorías productos <span>y compra el que más te guste</span></p>
            </div>
            
            {% if categoria_list %}
            <ul class="nav nav-tabs d-flex justify-content-center" data-aos="fade-up" data-aos-delay="200">
                {% for categoria in categoria_list %}
                <li class="nav-item">
                    <a class="nav-link {% if forloop.first %}active show{% endif %}" 
                        data-bs-toggle="tab" 
                        data-bs-target="#categoria-{{ categoria.id }}">
                        <h4>{{ categoria.nombre }}</h4>
                    </a>
                </li>
                {% endfor %}
            </ul>

            <div class="tab-content" data-aos="fade-up" data-aos-delay="300">
                {% for categoria in categoria_list %}
                <div class="tab-pane fade {% if forloop.first %}active show{% endif %}" id="categoria-{{ categoria.pk }}">
                    <div class="tab-header text-center">
                        <p>Arequipa</p>
                        <h3>{{ categoria.nombre }}</h3>
                    </div>
            
                    <div class="row gy-5">
                        {% for producto in categoria.producto_set.all %}
                        <div class="col-lg-4 menu-item">
                            <a href="{{ producto.get_absolute_url }}" class="glightbox"><img src="{% static producto.imagen %}" class="menu-img img-fluid" alt=""></a>
                            <h4>{{ producto.nombre }}</h4>
                            <p class="ingredients">
                                {{ producto.descripcion }}
                            </p>
                            <p class="price">
                                {{ producto.precio }}
                            </p>
                            <form action="{{ producto.get_absolute_url }}" method="get" class="php-email-form">
                                <div class="form-group">
                                    <button type="submit" class="btn btn-primary btn-block">Ver y Comprar</button>
                                    <input type="hidden" name="next" value="{{ next }}">
                                </div>
                            </form>
                        </div>
                        {% endfor %}
                    </div>
                </div>
                {% endfor %}
            </div>
            
            {% else %}
            <p>Lo sentimos, no hay productos disponibles ahora</p>
            {% endif %}
            <script>
                document.addEventListener("DOMContentLoaded", function() {
                    const tabLinks = document.querySelectorAll('.nav-link[data-bs-toggle="tab"]');
                    tabLinks.forEach(function(link) {
                        link.addEventListener("click", function(event) {
                            event.preventDefault();
                            const target = this.getAttribute("data-bs-target");
                            const tabContents = document.querySelectorAll('.tab-pane');
                            tabContents.forEach(function(content) {
                                content.classList.remove("active", "show");
                            });
                            const activeTab = document.querySelector(target);
                            activeTab.classList.add("active", "show");
                            tabLinks.forEach(function(link) {
                                link.classList.remove("active", "show");
                            });
                            this.classList.add("active", "show");
                        });
                    });
                });
            </script>
            
        </div>
    </section>
{% endblock %}

tiendaAqp/cafeteria/templates/cafeteria/cliente_create.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<section id="book-a-table" class="book-a-table">
    <div class="container" data-aos="fade-up">
        <div class="section-header">
            <h2>Registro</h2>
            <p>Únete a nuestra<span> comunidad</span>.</p>
        </div>

        <div class="row g-0">
            <div class="col-lg-6 reservation-img" style="background-image: url({% static 'img/latte.png' %});"
                data-aos="zoom-out" data-aos-delay="200">
            </div>
            
            <div class="col-lg-6 d-flex align-items-center reservation-form-bg">
                
                <div class="book-a-table" style="font-weight: 600; background: #df1529; color: white; text-align: center">
                {% for message in messages %}
                <h3>{{ message }}</h3>
                {% endfor %}
                </div>

                <form method="POST"  class="php-email-form"> 
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="{{ form.nombre.id_for_label }}">{{ form.nombre.id_for_label }}</label>
                        {{ form.nombre }}
                    </div>
                    <div class="form-group">
                        <label for="{{ form.email.id_for_label }}">{{ form.email.id_for_label }}</label>
                        {{ form.email }}
                    </div>
                    <div class="form-group">
                        <label for="{{ form.telefono.id_for_label }}">{{ form.telefono.id_for_label }}</label>
                        {{ form.telefono }}
                    </div>
                    {% if form.errors %}
                    <div class="alert alert-danger">
                        {% for error in form.non_field_errors %}
                        {{ error }}
                        {% endfor %}
                    </div>
                    {% endif %}
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary btn-block">Registrarte</button>
                        <input type="hidden" name="next" value="{{ next }}">
                    </div>
                    
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

tiendaAqp/cafeteria/templates/cafeteria/pedido_detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<section id="pedido-detail" class="pedido-detail">
    <div class="container" data-aos="fade-up">

        <div class="section-header">
            <h2>Detalles del Pedido</h2>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <div class="pedido-info">
                    <h3>Productos en el Pedido</h3>
                    <ul>
                        {% for item in object.itempedido_set.all %}
                        <li>{{ item.producto.nombre }} - Cantidad: {{ item.cantidad }}</li>
                        {% endfor %}
                    </ul>
                    <h3>Total a Pagar</h3>
                    <p class="precio">{{ object.total_monto }}</p>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

tiendaAqp/cafeteria/templates/cafeteria/pedido_list.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div class="container">
        <h2 class="mb-4">Tu Carrito de Compras</h2>
        {% if pedido_list %}
            {% for pedido in pedido_list %}
            <table class="table table-striped">
        <div class="section-header">
            <p>{{ cliente }}</p>
        </div>
                <thead>
                    <tr>
                        <th>Pedido</th>
                        <th>Producto</th>
                        <th>Cantidad</th>
                        <th>Precio unitario</th>
                        <th>Total</th>
                    </tr>
                </thead>
                <tbody>
                    {% for itempedido in pedido.itempedido_set.all %}
                        <tr>
                            <td>{{ itempedido.pedido }}</td>
                            <td>{{ itempedido.producto }}</td>
                            <td>{{ itempedido.cantidad }}</td>
                            <td>${{ itempedido.producto.precio }}</td>
                            <td>${{ itempedido.subtotal }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            <p><strong>Nuestro cliente:</strong> {{ pedido.cliente }}</p>
            <p><strong>Estado de entrega:</strong> {{ pedido.get_estado_display }}</p>
            <p><strong>Fecha del pedido:</strong> {{ pedido.fecha }}</p>

            <p class="mb-4"><strong>Total del pedido:</strong> ${{ pedidos_monto_total }}</p>

            {% endfor %}
        {% else %}
            <p class="mt-4">No tienes pedidos en tu carrito...</p>
        {% endif %}
    </div>
{% endblock %}

tiendaAqp/cafeteria/templates/cafeteria/producto_detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<section id="producto-detail" class="producto-detail">
    <div class="container" data-aos="fade-up">

        <div class="section-header">
            <h2>{{ producto.categoria.nombre }}</h2>
            <p>{{ producto.nombre }}</p>
        </div>

        <div class="row">
            <div class="col-lg-6">
                <img style="width: 600px; height: 350px; object-fit: cover;" src="{% static producto.imagen %}" class="img-fluid producto-img" alt="{{ producto.nombre }}">
            </div>
            <div class="col-lg-6">
                <div class="producto-info">
                    <h3>Descripción</h3>
                    <p>{{ producto.descripcion }}</p>
                    <h3>Precio</h3>
                    <p class="precio">{{ producto.precio }}</p>
                    <h3>Categoría</h3>
                    <p>{{ producto.categoria.nombre }}</p>
                    <form id="comprar-form" action="{% url 'hacer_pedido' %}" method="post" class="php-email-form">
                        {% csrf_token %}
                        <div class="form-group">
                            <button id="comprar-btn" type="button" class="btn btn-primary btn-block">Comprar</button>
                        </div>
                        <div id="cantidad-input" style="display: none;">
                            <input type="hidden" name="producto_id" value="{{ producto.id }}">
                            <hr>
                            <label for="nombre">Nombre:</label>
                            <input type="text" name="nombre" id="nombre" placeholder="Ingresa tu nombre de registro">
                            <hr>
                            <label for="email">Email:</label>
                            <input type="email" name="email" id="email" placeholder="Ingresa tu email de registro">
                            <hr>
                            <label for="cantidad">Cantidad:</label>
                            <input type="number" name="cantidad" id="cantidad" min="1" value="1">
                            <button type="submit" class="btn btn-success">Confirmar Compra</button>
                        </div>
                    </form>
                    <script>
                        document.addEventListener('DOMContentLoaded', function() {
                            const comprarBtn = document.getElementById('comprar-btn');
                            const cantidadInput = document.getElementById('cantidad-input');
                        
                            comprarBtn.addEventListener('click', function() {
                                comprarBtn.style.display = 'none';
                                cantidadInput.style.display = 'block';
                            });
                        });
                        </script>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

tiendaAqp/cafeteria/templates/cafeteria/producto_list.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <section id="menu" class="menu">
        <div class="container" data-aos="fade-up">

            <div class="section-header">
                <h2>Lo que ofrecdemos</h2>
                <p>Revisa a detalle los productos <span>y compra el que más te guste</span></p>
            </div>
            {% if producto_list %}
            <div class="tab-content" data-aos="fade-up" data-aos-delay="300">
                <div class="tab-pane fade active show" id="menu-starters">
                    <div class="row gy-5">
                        {% for producto in producto_list %}
                        <div class="col-lg-4 menu-item">
                            <a href="{{ producto.get_absolute_url }}" class="glightbox"><img src="{% static producto.imagen %}" class="menu-img img-fluid" alt=""></a>
                            <h4>{{ producto.nombre }}</h4>
                            <p class="ingredients">
                                {{ producto.descripcion }}
                            </p>
                            <p class="price">
                                {{ producto.precio }}
                            </p>
                            <form action="{{ producto.get_absolute_url }}" method="get" class="php-email-form">
                                <div class="form-group">
                                    <button type="submit" class="btn btn-primary btn-block">Ver y Comprar</button>
                                    <input type="hidden" name="next" value="{{ next }}">
                                </div>
                            </form>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            {% else %}
            <p>Lo sentimos, no hay productos disponibles ahora</p>
            {% endif %}

        </div>
    </section>
{% endblock %}

tiendaAqp/cafeteria/templates/cafeteria/reservamesa.html
{% extends "base.html" %}

{% load static %}

{% block content %}
    <section id="book-a-table" class="book-a-table">
        <div class="container" data-aos="fade-up">

        <div class="section-header">
            <h2>Book A Table</h2>
            <p>Book <span>Your Stay</span> With Us</p>
        </div>

        <div class="row g-0">

            <div class="col-lg-4 reservation-img" style="background-image: url(static/img/reservation.jpg);" data-aos="zoom-out" data-aos-delay="200"></div>

            <div class="col-lg-8 d-flex align-items-center reservation-form-bg">
            <form action="{% static 'forms/book-a-table.php'%}" method="post" role="form" class="php-email-form" data-aos="fade-up" data-aos-delay="100">
                <div class="row gy-4">
                <div class="col-lg-4 col-md-6">
                    <input type="text" name="name" class="form-control" id="name" placeholder="Your Name" data-rule="minlen:4" data-msg="Please enter at least 4 chars">
                    <div class="validate"></div>
                </div>
                <div class="col-lg-4 col-md-6">
                    <input type="email" class="form-control" name="email" id="email" placeholder="Your Email" data-rule="email" data-msg="Please enter a valid email">
                    <div class="validate"></div>
                </div>
                <div class="col-lg-4 col-md-6">
                    <input type="text" class="form-control" name="phone" id="phone" placeholder="Your Phone" data-rule="minlen:4" data-msg="Please enter at least 4 chars">
                    <div class="validate"></div>
                </div>
                <div class="col-lg-4 col-md-6">
                    <input type="text" name="date" class="form-control" id="date" placeholder="Date" data-rule="minlen:4" data-msg="Please enter at least 4 chars">
                    <div class="validate"></div>
                </div>
                <div class="col-lg-4 col-md-6">
                    <input type="text" class="form-control" name="time" id="time" placeholder="Time" data-rule="minlen:4" data-msg="Please enter at least 4 chars">
                    <div class="validate"></div>
                </div>
                <div class="col-lg-4 col-md-6">
                    <input type="number" class="form-control" name="people" id="people" placeholder="# of people" data-rule="minlen:1" data-msg="Please enter at least 1 chars">
                    <div class="validate"></div>
                </div>
                </div>
                <div class="form-group mt-3">
                <textarea class="form-control" name="message" rows="5" placeholder="Message"></textarea>
                <div class="validate"></div>
                </div>
                <div class="mb-3">
                <div class="loading">Loading</div>
                <div class="error-message"></div>
                <div class="sent-message">Your booking request was sent. We will call back or send an Email to confirm your reservation. Thank you!</div>
                </div>
                <div class="text-center"><button type="submit">Book a Table</button></div>
            </form>
            </div><!-- End Reservation Form -->

        </div>

        </div>
    </section>
    
{% endblock %}